//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignmnt
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcity
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> sid { get; set; }
    
        public virtual tblstate tblstate { get; set; }
    }
}
